version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ~/PhpstormProjects/${PROJECT_NAME}/bedrock:/var/www/html:rw,cached
      - ./certs:/etc/certs
    depends_on:
      - wordpress
    restart: always

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    volumes:
       - ~/PhpstormProjects/${PROJECT_NAME}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    restart: always
    ports:
      - '3306:3306'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-wordpress
    volumes:
      - ~/PhpstormProjects/${PROJECT_NAME}/bedrock:/var/www/html:rw,cached
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - WORDPRESS_DB_NAME=${DATABASE_NAME}
      - WORDPRESS_TABLE_PREFIX=${DATABASE_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - mysql
    restart: always

  composer:
    image: composer/composer
    container_name: ${PROJECT_NAME}-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ~/PhpstormProjects/${PROJECT_NAME}/bedrock:/var/www/html:rw,cached


volumes:
  database:
    driver: local


